.
create or replace function public.is_admin()
returns boolean
language sql
stable
as $$
    select coalesce(auth.jwt() ->> 'email', '') = 'COLOQUE_SEU_EMAIL_AQUI'
$$;


create table if not exists public.produtos (
    id bigint generated by default as identity primary key,
    nome text not null,
    categoria text not null,
    preco numeric(10,2) not null check (preco >= 0),
    imagem text not null,
    descricao text not null,
    material text,
    dimensoes text,
    peso text,
    origem text,
    sobre text,
    eco text,
    imagens jsonb not null default '[]'::jsonb,
    ativo boolean not null default true,
    created_at timestamptz not null default now()
);

alter table public.produtos enable row level security;

drop policy if exists "produtos_leitura_publica" on public.produtos;
create policy "produtos_leitura_publica" on public.produtos
    for select using (ativo = true);

drop policy if exists "produtos_admin_tudo" on public.produtos;
create policy "produtos_admin_tudo" on public.produtos
    for all to authenticated
    using (public.is_admin()) with check (public.is_admin());

drop policy if exists "pedidos_admin_select" on public.pedidos;
create policy "pedidos_admin_select" on public.pedidos
    for select to authenticated using (public.is_admin());

drop policy if exists "pedidos_admin_update" on public.pedidos;
create policy "pedidos_admin_update" on public.pedidos
    for update to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "pedidos_admin_delete" on public.pedidos;
create policy "pedidos_admin_delete" on public.pedidos
    for delete to authenticated using (public.is_admin());

insert into public.produtos (id, nome, categoria, preco, imagem, descricao, material, dimensoes, peso, origem, sobre, eco)
overriding system value
values
    (1, 'Vaso de Bambu', 'Vasos', 59.9, 'imagens/bambu.jpg', 'Peça natural para trazer acolhimento e leveza ao ambiente.', 'Bambu natural', '18 × 18 × 22 cm', '600 g', 'Produção artesanal sustentável', 'Vaso feito de bambu, material de crescimento rápido e renovável. Traz textura natural e leveza para estantes, mesas e cantos da casa.', 'Bambu é uma das matérias-primas que mais rápido se renova na natureza.'),
    (2, 'Luminária Ondulada', 'Luminárias', 89.9, 'imagens/luminaria.jpg', 'Iluminação criativa com design ondulado e luz aconchegante.', 'Madeira reaproveitada', '28 × 28 × 30 cm', '750 g', 'Produção artesanal sustentável', 'Luminária com design ondulado que espalha uma luz quente e aconchegante, ótima para quartos, salas e cantos de leitura.', 'Feita com madeira de aproveitamento, reduzindo o desperdício.'),
    (3, 'Almofada Orgânica', 'Almofadas', 79.9, 'imagens/almofada.jpg', 'Conforto e personalidade com bordado em relevo e cores vibrantes.', 'Fios de algodão', '45 × 45 cm', '500 g', 'Produção artesanal', 'Almofada com bordado em relevo e cores vibrantes, que dá personalidade a sofás, camas e poltronas.', 'Confeccionada com sobras de fios e produção em pequenos lotes.'),
    (4, 'Bambu da Sorte', 'Vasos', 69.9, 'imagens/bambu-sorte-pedras.jpg', 'Vidro, madeira e pedras decorativas para um cantinho verde.', 'Vidro, madeira e pedras', '15 × 15 × 25 cm', '700 g', 'Produção artesanal sustentável', 'Conjunto com recipiente de vidro, base de madeira e pedras decorativas para um cantinho verde em qualquer ambiente.', 'Planta cultivada em água, sem necessidade de substrato descartável.'),
    (5, 'Almofada Colmeia', 'Almofadas', 84.9, 'imagens/almofada-colmeia.jpg', 'Crochê artesanal com abelhinhas em relevo e muito charme.', 'Crochê de algodão', '40 × 40 cm', '450 g', 'Crochê artesanal', 'Almofada de crochê feita à mão, com abelhinhas em relevo e muito charme.', 'Trabalho manual com fibras naturais e baixo consumo de energia.'),
    (6, 'Bambu Duplo de Mesa', 'Vasos', 44.9, 'imagens/bambu-sorte-madeira.jpg', 'Dois tubos de vidro sobre base de madeira, ideal para mesas.', 'Vidro e madeira', '20 × 10 × 24 cm', '550 g', 'Produção artesanal sustentável', 'Dois tubos de vidro sobre base de madeira, ideais para mesas, bancadas e escritórios.', 'Peça reutilizável e durável, pensada para evitar descarte.'),
    (7, 'Kit de Vasos Suspensos', 'Vasos', 99.9, 'imagens/vasos-suspensos.jpg', 'Vasos de bambu para pendurar e decorar com flores naturais.', 'Bambu', 'Kit com 3 vasos, 12 × 12 × 15 cm cada', '900 g', 'Produção artesanal sustentável', 'Kit de vasos de bambu para pendurar, perfeito para compor jardins verticais com flores naturais.', 'Bambu natural, renovável e biodegradável.'),
    (8, 'Porta-Vinhos de Madeira', 'Acessórios', 79.9, 'imagens/porta-vinhos-madeira.jpg', 'Suporte artesanal de madeira para acomodar garrafas com charme e praticidade.', 'Madeira maciça', '35 × 14 × 20 cm', '1,1 kg', 'Marcenaria artesanal', 'Suporte artesanal de madeira que acomoda garrafas com charme e praticidade.', 'Madeira com origem responsável e acabamento sem excesso de químicos.'),
    (9, 'Luminária Rústica Suspensa', 'Luminárias', 149.9, 'imagens/luminaria-madeira-pendurada.jpg', 'Composição de madeira e lâmpadas decorativas para uma iluminação acolhedora.', 'Madeira e lâmpadas decorativas', '60 × 25 × 40 cm', '1,3 kg', 'Produção artesanal sustentável', 'Composição suspensa de madeira e lâmpadas decorativas para uma iluminação acolhedora.', 'Compatível com lâmpadas LED de baixo consumo.'),
    (10, 'Luminária Escultural de Madeira', 'Luminárias', 129.9, 'imagens/luminaria-madeira-vazada.jpg', 'Peça de madeira vazada que cria sombras e uma atmosfera aconchegante.', 'Madeira vazada', '30 × 30 × 35 cm', '1 kg', 'Produção artesanal sustentável', 'Peça escultural de madeira vazada que desenha sombras e cria uma atmosfera aconchegante.', 'Corte aproveitando ao máximo cada chapa de madeira.'),
    (11, 'Kit Spa Natural', 'Bem-estar', 69.9, 'imagens/kit-spa-natural.jpg', 'Conjunto de cuidados pessoais com itens naturais para momentos de relaxamento.', 'Ingredientes naturais', 'Kit com 4 itens', '480 g', 'Produção consciente', 'Conjunto de cuidados pessoais com itens naturais para momentos de relaxamento.', 'Itens de origem natural em embalagem reciclável.'),
    (12, 'Bálsamos Naturais', 'Bem-estar', 39.9, 'imagens/balsamos-naturais.jpg', 'Seleção de bálsamos em embalagens compactas, pensada para cuidados do dia a dia.', 'Bálsamos naturais', 'Embalagens de 15 g', '120 g', 'Produção consciente', 'Seleção de bálsamos em embalagens compactas, pensada para os cuidados do dia a dia.', 'Embalagens compactas e recicláveis.'),
    (13, 'Kit de Garrafas de Bambu', 'Acessórios', 89.9, 'imagens/garrafas-bambu.jpg', 'Conjunto de recipientes reutilizáveis com detalhes em bambu para acompanhar sua rotina.', 'Bambu e vidro', 'Kit com 3 garrafas, 7 × 7 × 22 cm cada', '850 g', 'Produção sustentável', 'Conjunto de recipientes reutilizáveis com detalhes em bambu para acompanhar sua rotina.', 'Substitui descartáveis, reduzindo o lixo plástico.'),
    (14, 'Tigelas de Fibra de Coco', 'Acessórios', 59.9, 'imagens/tigelas-coco.jpg', 'Tigelas artesanais produzidas com fibra de coco para uma composição natural.', 'Fibra de coco', 'Diâmetro de 12 cm', '300 g', 'Produção artesanal sustentável', 'Tigelas artesanais de fibra de coco para uma composição natural na mesa ou na decoração.', 'Fibra de coco é um subproduto aproveitado, que seria descartado.'),
    (15, 'Kit de Autocuidado Sustentável', 'Bem-estar', 74.9, 'imagens/kit-autocuidado-sustentavel.jpg', 'Itens reutilizáveis para uma rotina de autocuidado mais consciente.', 'Materiais reutilizáveis', 'Kit com 5 itens', '600 g', 'Produção consciente', 'Itens reutilizáveis para uma rotina de autocuidado mais consciente.', 'Cada item substitui um equivalente descartável.'),
    (16, 'Kit de Higiene em Bambu', 'Acessórios', 54.9, 'imagens/kit-higiene-bambu.jpg', 'Conjunto de acessórios de higiene com materiais de inspiração natural e embalagem sustentável.', 'Bambu', 'Kit com 4 itens', '250 g', 'Produção sustentável', 'Conjunto de acessórios de higiene de inspiração natural, em embalagem sustentável.', 'Bambu biodegradável no lugar do plástico.'),
    (17, 'Caneca Cerâmica Sol', 'Acessórios', 64.9, 'imagens/caneca-ceramica-solar.jpg', 'Caneca artesanal com estampa solar para trazer cor e personalidade ao cotidiano.', 'Cerâmica artesanal', '9 × 9 × 10 cm (300 ml)', '380 g', 'Produção artesanal', 'Caneca artesanal com estampa solar, para trazer cor e personalidade ao cotidiano.', 'Peça durável e reutilizável, feita em pequenos lotes.')
on conflict (id) do nothing;

select setval(pg_get_serial_sequence('public.produtos', 'id'),
              (select coalesce(max(id), 1) from public.produtos));
