create table public.pedidos (
    id bigint generated by default as identity primary key,
    codigo_pedido text not null unique,
    nome_cliente text not null,
    telefone text not null,
    endereco_entrega text not null,
    forma_pagamento text not null,
    observacoes text,
    subtotal numeric(10,2) not null,
    entrega numeric(10,2) not null default 10.00,
    total numeric(10,2) not null,
    status text not null default 'Pendente',
    status_pagamento text not null default 'Nao processado',
    itens jsonb not null,
    created_at timestamptz not null default now()
);

-- Para o trabalho acadêmico, avalie as políticas RLS
-- antes de permitir inserções públicas.
-- Não libere SELECT público para dados pessoais de clientes.
